{
 "title": "Flask App + Kubernetes Monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "CPU usage Flask (segundos totales)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m])",
     "legendFormat": "cpu usage"
    }
   ]
  },
  {
   "title": "Latencia promedio (segundos)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_sum[1m]) / rate(flask_http_request_duration_seconds_count[1m])",
     "legendFormat": "avg latency"
    }
   ]
  },
  {
   "title": "Requests por segundo",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(flask_http_request_total[1m])",
     "legendFormat": "req/s"
    }
   ]
  },
  {
   "title": "CPU por contenedor",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace='default', pod=~'flask-api.*'}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Estado de pods (Running / Pending)",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_status_phase{namespace='default'}",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Memoria usada por Flask (Bytes)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "mem usage" }
   ]
  },
  {
   "title": "Memoria por contenedor",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace='default', pod=~'flask-api.*'}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}